version: "3"

services:
  postgres:
    container_name: db-local-fm
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: fm
      POSTGRES_DB: public
